workflows:
  biketravelart-ios-workflow:
    name: Biketravelart iOS Workflow
    # instance_type: mac_mini
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"                
        # https://docs.codemagic.io/code-signing-yaml/signing-ios/
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmhJNWNwYjJDSG00eE54UnNqN2ZWcTlQRTdCOW8wVkFUZVRITlZ3akZNLUwyOGxhWVloTjd2cmV1cjU1WHFDX1Q4a0ltQmR2SUpOel9iZERwTnNNanQ2ZGlmS2Zydi1DS0wyWVBWM1pFZDB6TXNmeXNMNmlmRmU3b0wtUG05bFlCdkNrVlQ=)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmhJNWVmdXI0alNKT2Q4Q1drNGFZSVBxekpkS2tES1VVNmJsM1EyVUZYelMtUUU2VDZvTXZzRzhyYU1QUWcyX0xiaTN2ZWYySVREay1hM045NURJVWtSMEFVcmc9PQ==) 
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhJNXV5RElfdVNxeVVscUNrN0d0bzNvUERXSUZpVnlEVnFtTXh4UnlTR0tFZ0didXNIM3VwVHM4S1c3RlZjdC05T1NZNnNsbFJybnFpdDNtal9pSGN3aEhBVHNJWW5JMlpkbW5ZUHFuNE9qUi1VMmg3dXB6Q2RiWkl1dEY1NDRlTzU3RWprZjRwTzJFbGwwT29MV05Wa2hTeUM0dFpOS1ZCY1d4VG1kNTZMUjFLdUVOVGpKb3Etc2xVaVcwS2RNQUJqN21XWnVhd3F0Ujh0Yy1LblJ2bGdmSGQ2eTJkNHdoYlZGc0dJNDdfbjJXWV9YWl9XcWRrV0VpbEVFT0lzWk1QUzBwN2pPZUV4d0Z1Z2pfdXZFaUlhVXdHYTZRUlR6b1RYUGxBYVlPSld6b1ROYmVsMDAwbGFFYTJOb3NQZGY5UkNhbl9KZ2RxdGhZUEtCdjJOMWgzMzZyM2d3NUNXYW5ENk00NHpITWdKS3ZoTXVrcjlnSlNOekNJNmJlQTVSVGxqZ1BKc1poYk1wekd6bnJub2tuVC1jcmxZVENyUnlFODhibU1lVUpsOUdIeE5iRT0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhJNkx2VXBuY25GRzFpeDUwcE11UFM1aFlvbTMyOFZacFJHdHUtdVhaYTJkTWQzWlFkdThxWFcwejJwMVppQ3pzVVRoOWo4VG9HcDIzN2JJRDZQdTN4aDI1X2s2NTVwdWJKYkl0dDNleGV0N3Y1eUJybWdiVTBhZUpGUUVxelp5Q2NKclZBdjkwajRtUU9tMWtGWDRZSjZQTmZGZHgyemhPYnpUUHJCTnJEUUFWYnNyQ3VyVjU0NTE5bm1FQ0VSdjJ0Uk9Mc1VNbHE2c0M3bzB1dVNZSmY1Q2VyTWxTZzFQSGNtNmVVUDQ1T2c5VGh4ajFmZ04xMjV0Sm1hVEJ6TWlPU3FCWGhyVmZzLUdtVmhNbzdhU2ZCNVY4MEljeHVuYXpKaHJsTHEtVkFZZGtUeVh5TkE0Y3plZTdBZFNkZzBRVkJ5dGh5ZFlHbXdlUnJhQl9zUkhmSlg1R3U3WjhZdXBWSHlxdUIwb0RGT1pPYlFfRGJpYy0xdWt3TXBiNVlPSlhrcS1xelA0V2FFTjZ1T2EwdDBJTzg3dk5Vay1tSkQ5YnNSdllGYzV5OHA3bktKR2ZnT2JTTjRIclN5aW4ySWlZZW9CYm1wcjRUY0YzcmVyZEdvVUZlc2hFSUhVS2VyWjVLX2pSRE14SDlzQVRIOVY1RXBCOTMxNWFNYVN1bE1saDNLdXU5b2hyd1RTUGNHSjBCZF9HazFPakUtSlhTY1V2cEpiSlQ2dHVLVTFCN3JhSDl5bVYyNmt4TWUyUXBwOElKU3l4V2F3Rmk5SElNQVVfcjZMZFV3bTBYMl9ZT29JUDdxR0N5ZlB1LTNLQ2poMC1HNF9SdmxLRGVFM2xjdy0wWXhvRzFhN1F4eHhncnJvRmhuNC00YldZbEkzMUhRVzhSbnBFaTF6Wnk0bDd3T2FwSlU2LUlJd1l6TjBxc01Fc1IxX1ZTT2lGMi1fX3B5NjJ6RHNZNG40cExIelZwSFdMc3FwNlFBYjlTQlp3WDJfa2RuRlZjQlVvbHZfZmR1Y3gya1dSSnhVeVlLa3RXTjBuaE5neW9yVzNub3dqc2JFWXhfQWRmNGFmRjRUdmY4b0xIWFdWNXd0VFQtdDB2U2hRREdqNUlYX3lzdUlIV2huQlV0bk9rWjJDc1RjcWhIRmNDSmdHTVFOU05LUDlxdXp5TTltbzRUUXUyOGk2ZngyMXMtWXprWjJwejIxVEZDTlB2MWNQZ1RwdzIzeEJ6cFkxZjhPWFk0TkZfNDJycnlNT1M4SDNPTVU2Vno3OVN0aGFRWktCem1SQWZ0SEVaZW9FblZaRXNkZ0JOT05BdzZmU01FTk9RaTd2U2lWbm5jVFZBSnk1UXNpYmY3a2ttS1prVmlxZmVZWHVkTDNiSkNvZlA3UEJ2RE1MX2szMmJsS29OOTFtalZ6RHFZQVd3VmNJbjI1enRBeTBNRzJ0MldMTHpESXJ1cDdQSTI1eVJ3RFl6dG5fYXVOMWpaX0FqVHE5T2hjWlNjd25OeVNBSGdWZHNralhCODJhcTQtSlpKaUN1MzBJMzJQem44WHR0dVd2d0VsZktXZV84bVBIVV9NaGFaS0pWODdyWlRHRThlbkhHdjlWdVlxTkVMdk9IRnV2dERveWdlSTg0MEJIb1M0VEZDLVlMWlg1LTk1SlhLYmxJM3BSNHZXcW9oRzdnai16VGVSSlhuUzdjQUxPaElPU0JKcUFxNXQ4LWQ0SnI0LUx0RGVZTFVJazZtUEFYWkotTE1UbUtfbDNsemRhZzJyR25ObDBaVEh1RnFBUEVuNWZfNWE3TVpJclo1MXEwNlZaczE1QTJuX3M1VGd5Q3RZaWJiT3VxZ1Bzb2lMTkhiQllVQ0pNbkt6LXUxU3lyQzU5RHpocXJuN0h2dG5XSFFldkhKTGJEVmNTRnBZb2diY1NtcXNMM0E5MWtDTUJZTGpxVDVfaWlKSm5JMmkycnA1Wk9FY3lrdXRKZjhjRHl1V2sxOHJjNWhkSzdHc1VpZ1JDaHYyZkJybG84a0M2c2JLZE9HQ00zT3J2cnkxNzhkeEVIMXVfR29uempJM1RIZm9rNS1QcEVxa19mQVpjWnNVN0FId1VIanlsTEZZbFg1Qmh1NEV6WEhCZmlRbDFyeXgxelFZOFJZWnhoY0QtUFgtd2d3N3k2NXczY09zMWpvRHFPc05XdS1IVnpvcTBIZFA1WUVvZk40T1RESWpGNTVEUmU1N1lyUHc3Q3dkeWpqazVLSzFYZk5sQmZEZmZQRzhNMHpicGtIenpfb2RpdHdaS2cxYkVlOWU1VlRLcGZOZWE2Q08xYUVYZTZnSExZLXpqanhkdWdqQVF5blpBOWFEYV8zRHdfb2ZqWTRlX0U1dmhhVG9YeE1fQXZGQWZzc084M05WY1c5bVpCSWZKRkdQcEZyR05mN3VMdDZGcl9XaHdaU05MX2JBeTFSbm91UHhWSDFhYms1aTh2N3hJX2RXOGNpcEtFY05wU1E0WWc1ZkMzZVVLbm0wXy1qVkY2YzdDVjdLSXN4NG54UXBoSXgxVWZ1UnVRUl96OXZnTkd5Z3lzVG5uM0MtSDdnSUJlM2ZYY01GYVRiRmlRdHJpb3NCMDAtNGtzekdjWXdEdmw5ZmlNNjF4VzVFWG5SUkJabkFhTlhsUHNkYWxtaXZzRVhsVXpaVWVUMjNjZGE0NEtWVGFVWDUzV0I5a2VtRnk0MEpocnF2V0hGbjNBaWdUU0xLSzNVclBxczZ6d1Y2dHpDbXlfcUo0STE2TnNzNjFOWEVQSUNpSVVWOHdaMW85TGo3UWtBbDVXamFnb094RkphTkM1U2hodWliUnFQUGY0SF9vaFhZbENmOGwySzViaHRYeWdjQmc1UVM2TlViU1V1Zk02Ui1iTGRjbEFlc1FtMVhkVWRyYmN2Rlhfb1psSldDLVFKMmhZc0tBbVpoUnJna1IzVXJVS3FqVEtRWjlJV204SlBqNzM2RlV5WU05ajdkUkgwbDg0QjV2ZkE0MllOeDVkallqeXdCaHRVVmM3ZUlsR09uallYanM4Q0lWeHJIVG5KQmZfT3JQcUI4dGxWX1pRVmZT) 
        BUNDLE_ID: "io.codemagic.flutteryaml" # <-- Put your bundle id here
        APP_STORE_ID: 11111111110 # <-- Use the TestFlight Apple id number (An automatically generated ID assigned to your app) found under General > App Information > Apple ID. 
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
                    keychain initialize
      - name: Fetch signing files
        script: |
                    app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
                    keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
                    xcode-project use-profiles
      - name: Get Flutter packages
        script: |
                    cd . && flutter packages pub get
      - name: Flutter analyze
        script: |
                    cd . && flutter analyze
      - name: Flutter unit tests
        script: |
                    cd . && flutter test
        ignore_failure: true          
      - name: Install pods
        script: |
                    find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist          
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - greatriversnet@gmail.com
          - greatriversnet@yahoo.co.uk
        notify:
          success: true     # To receive a notification when a build succeeds
          failure: false    # To not receive a notification when a build fails
      slack: 
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: "#builds"
        notify_on_build_start: true   # To receive a notification when a build starts
        notify:
          success: true               # To receive a notification when a build succeeds
          failure: false              # To not receive a notification when a build fails
      app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution              
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY   
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: 21d78e2f-b8ad-...  # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
       
