# Customize the codemagic.yaml file according to your project and commit it to the root of your repository
# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
workflows:
  greatrivers-workflow:
    name: GreatRivers Workflow
    scripts:
      - name: Biketravelart
        script: echo "Hello Codemagician!"
    publishing:
      email:
        recipients:
          - greatriversnet@yahoo.co.uk