workflows:
  biketravelart-workflow:
    name: Biketravelart iOS
    instance_type: mac_mini
    max_build_duration: 120
    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"
        SECRET_ENV_VAR: Encrypted(...)
    
    # iOS automatic code signing
    APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
    APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
    APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
    CERTIFICATE_PRIVATE_KEY: Encrypted(...)
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - greatriversnet@gmail.com
      scripts:
        - echo 'Welcome to the world of Biketraavelart'