workflows:
  ios-code-signing:
    name: Biketravelart iOS
    instance_type: mac_mini
    max_build_duration: 120
    environment:
        vars:
          XCODE_WORKSPACE: "swiftly.xcworkspace" # <-- Put the name of your workspace here. 
          XCODE_SCHEME: "swiftly" # <-- Put the name of your scheme here.
          # Set up env vars for manual codesigning (See - https://docs.codemagic.io/code-signing-yaml/signing-ios/)
          CM_CERTIFICATE: 
          CM_PROVISIONING_PROFILE: 
          CERTIFICATE_PRIVATE_KEY: 
          # Env vars for automatic build versioning and publishing
          APP_STORE_CONNECT_ISSUER_ID: 
          APP_STORE_CONNECT_KEY_IDENTIFIER: 
          APP_STORE_CONNECT_PRIVATE_KEY: 
          APPLE_ID_EMAIL: 
          APP_SPECIFIC_PASSWORD: 
          APP_STORE_APP_ID: 
        PUBLIC_ENV_VAR: ""
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - greatriversnet@gmail.com
      scripts:
        - echo 'Welcome to the world of Biketraavelart'